http_interactions:
  - request:
      method: HEAD
      path: /data/v9/zarr/Organization_X/l4_sample/
      headers:
        host: localhost:9000
        accept: '*/*'
        accept-encoding: gzip, deflate
        user-agent: Python/3.13 aiohttp/3.10.11
      body:
        encoding: utf8
        data: ''
        compression: none
    response:
      status:
        code: 404
      headers:
        x-powered-by: Express
        cache-control: no-cache
        referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
        access-control-max-age: '600'
        access-control-allow-origin: '*'
        x-permitted-cross-domain-policies: master-only
        date: Fri, 12 Sep 2025 13:46:21 GMT
        connection: close
        content-type: application/json
        content-length: '215'
      body:
        encoding: utf8
        data: ''
        compression: none
  - request:
      method: GET
      path: /data/v9/zarr/Organization_X/l4_sample/
      headers:
        host: localhost:9000
        accept: '*/*'
        accept-encoding: gzip, deflate
        user-agent: Python/3.13 aiohttp/3.10.11
      body:
        encoding: utf8
        data: ''
        compression: none
    response:
      status:
        code: 404
      headers:
        x-powered-by: Express
        cache-control: no-cache
        referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
        access-control-max-age: '600'
        access-control-allow-origin: '*'
        x-permitted-cross-domain-policies: master-only
        date: Fri, 12 Sep 2025 13:46:21 GMT
        connection: close
        content-type: application/json
        content-length: '215'
      body:
        encoding: utf8
        data: >-
          {"messages":[{"error":"Datasource not found on datastore server. Might
          still be initializing."},{"chain":"[Server Time
          2025-09-12T13:46:21.831Z] Data source is not usable: Some(No longer
          available on datastore.)"}]}
        compression: none
